import { z } from 'zod';
import { insertHomeworkSchema, homework } from './schema';

export const errorSchemas = {
  validation: z.object({
    message: z.string(),
    field: z.string().optional(),
  }),
  notFound: z.object({
    message: z.string(),
  }),
  internal: z.object({
    message: z.string(),
  }),
};

export const api = {
  homework: {
    create: {
      method: 'POST' as const,
      path: '/api/homework',
      input: insertHomeworkSchema.omit({ content: true }), // Content is generated by server
      responses: {
        201: z.custom<typeof homework.$inferSelect>(),
        400: errorSchemas.validation,
        500: errorSchemas.internal,
      },
    },
    get: {
      method: 'GET' as const,
      path: '/api/homework/:id',
      responses: {
        200: z.custom<typeof homework.$inferSelect>(),
        404: errorSchemas.notFound,
      },
    },
    list: {
      method: 'GET' as const,
      path: '/api/homework',
      responses: {
        200: z.array(z.custom<typeof homework.$inferSelect>()),
      },
    },
  },
};

export function buildUrl(path: string, params?: Record<string, string | number>): string {
  let url = path;
  if (params) {
    Object.entries(params).forEach(([key, value]) => {
      if (url.includes(`:${key}`)) {
        url = url.replace(`:${key}`, String(value));
      }
    });
  }
  return url;
}

export type HomeworkInput = z.infer<typeof api.homework.create.input>;
